apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: common-nmstate
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/common/nmstate
    repoURL: https://github.com/leifmadsen/osp-k8s-architecture
    targetRevision: HEAD
  syncPolicy:
    automated: {}
