resources:
  - ../../base

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: osp-worker-0
    patch: |-
      - op: replace
        path: /metadata/name
        value: stackops-6fszw-worker-0-cp5mf
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: osp-worker-1
    patch: |-
      - op: replace
        path: /metadata/name
        value: stackops-6fszw-worker-0-llzs9
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: osp-worker-2
    patch: |-
      - op: replace
        path: /metadata/name
        value: stackops-6fszw-worker-0-rgzj7
