resources:
  - openstack-service-secret.yaml
  - openstack-nncp.yaml
  - openstack-nad.yaml
  - openstack-ipaddresspools.yaml
  - openstack-l2advertisement.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: AnnotationsTransformer
    metadata:
      name: syncwave50
    annotations:
      argocd.argoproj.io/sync-wave: '-50'
    fieldSpecs:
    - kind: Secret
      name: osp-secret
      path: metadata/annotations
      create: true
    ---
    apiVersion: builtin
    kind: AnnotationsTransformer
    metadata:
      name: syncwave40
    annotations:
      argocd.argoproj.io/sync-wave: '-40'
    fieldSpecs:
    - kind: NodeNetworkConfigurationPolicy
      path: metadata/annotations
      create: true
